### ISSUE TITLE
Deprecation notice

### ISSUE THREAD

**Issue by ssipos90** [joelnb/ansible-ssmtp#1]
Hi,

I've installed your role and I got

```
[DEPRECATION WARNING]: "include" is deprecated, use include_tasks/import_tasks instead. This feature will
 be removed in version 2.16. Deprecation warnings can be disabled by setting deprecation_warnings=False
in ansible.cfg.
```
 
Thanks

**Comment by joelnb** [comment]
Hello, thanks for the report! I have corrected this now but just so you know it may be best not to use this module - SSMTP is not maintained any more so you may miss security updates. I have added a note to the README to help future readers become aware of this fact.

I have switched to MSMTP which is one of the alternatives recommended by the [Arch wiki](https://wiki.archlinux.org/title/Msmtp). If you want to do the same you could try my role for it: https://github.com/joelnb/ansible-msmtp

**Comment by ssipos90** [comment]
Thanks. I did go for msmtp by the end of that day, it's simpler.

Cheers
